# Generated by Django 3.0.5 on 2020-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('allDay', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('resourceId', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ('-start', '-end', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('eventBackgroundColor', models.CharField(default='#3788d8', max_length=50)),
                ('eventTextColor', models.CharField(default='#fff', max_length=50)),
                ('eventClassNames', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
