# Generated by Django 3.0.5 on 2020-04-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='all_day',
            new_name='allDay',
        ),
    ]
