# Generated by Django 3.0.5 on 2020-04-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0003_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_resource', to='fullcalendar.Resource'),
        ),
    ]
