# Generated by Django 3.0.5 on 2020-04-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0004_event_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='resource',
        ),
    ]
