# Generated by Django 3.0.5 on 2020-04-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0003_department_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('years', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cources.Department', verbose_name='direction_department')),
            ],
            options={
                'ordering': ('short_name',),
            },
        ),
    ]
